name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.0.26
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'

      - name: Upload Trivy results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.txt

